---
title: "Reproducible document"
author: "EBG"
format: html
editor: visual
---

## Basics of R

```{r}
1 + 1
```

## Setup code chunk

## About me

-   Erika B. Gram
-   Department of Clinical Research
-   University of Southern Denmark

I was born in **Sweden** and have lived in *Denmark* for 15 years.

## Simple code

```{r}
3 * 3
```

```{r setup}
#| message: false
#| warning: false
library(tidyverse)
post_meal_data <- read_csv2(
here::here("data/post-meal-insulin.csv")
)
```

## Showing the data

```{r}
post_meal_data
```

```{r}
glimpse(post_meal_data)
```

## Testing for Git

I don't think I follow what we are doing.

Again again

## Test 2

Will it work know?

```{r ggplot}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

```{r}
#| fig-cap: "BMI results"
#| label: fig-BMI_histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

@fig-BMI_histo

## Exercise Discrete Plots

```{r}
#| fig-cap: Jabadabado
#| label: fig-jabadabado
ggplot(post_meal_data, aes(x = glykemi)) + 
  geom_bar()
```
See @fig-jabadabado for a cool plot
